name: Homegear
version: '0.2'
slug: rpi-homegear
description: >-
  "Homegear as a Hassio add-on"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
url: https://github.com/mjahn/hassio-homegear-addon
ports:
  2001/tcp: 2001
  2002/tcp: 2002
  2003/tcp: 2003
map:
  - config:rw
  - share:rw
startup: services
boot: auto
gpio: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
environment: {}
options: {}
schema: {}
devices:
  - /dev/ttyAMA0:/dev/ttyAMA0:rwm
